services:
  postgres:
    env_file:
      - ./apps/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - ./apps/backend/.env
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin4:/var/lib/pgadmin4

  backend:
    container_name: rbo-backend-test
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    command: yarn run test:cov
    env_file:
      - ./apps/backend/.env
    ports:
      - "5555:5555"
      - "8080:8080"
  
  frontend:
    container_name: rbo-frontend-test
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    command: yarn run test
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3000:3000"
