services:
  postgres:
    env_file:
      - ./apps/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - ./apps/backend/.env
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin4:/var/lib/pgadmin4

  backend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    command: yarn run start:dev
    env_file:
      - ./apps/backend/.env
    ports:
      - "5555:5555"
      - "8080:8080"
    develop: # Funcionalidades de dev
      watch: # hot reload configs
        - action: sync
          path: ./apps/backend # pasta raíz do host
          target: /app # pasta raíz do container
          ignore:
            - ./apps/backend/node_modules/
            - ./apps/backend/prisma/
        - action: rebuild
          path: ./apps/backend/prisma
        - action: rebuild
          path: ./apps/backend/package.json
        - action: sync+restart
          path: ./apps/backend/.env
          target: /app/.env
  
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    command: yarn run dev
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3000:3000"
    develop: # Funcionalidades de dev
      watch: # hot reload configs
        - action: sync
          path: ./apps/frontend # pasta raíz do host
          target: /app # pasta raíz do container
          ignore:
            - ./apps/frontend/node_modules/
        - action: rebuild
          path: ./apps/frontend/package.json
        - action: sync+restart
          path: ./apps/frontend/.env
          target: /app/.env
