services:
  postgres:
    env_file:
      - ./apps/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    env_file:
      - ./apps/backend/.env
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin4:/var/lib/pgadmin4

  backend:
    container_name: rbo-backend-prod
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile.prod
    command: npm run start:prod
    env_file:
      - ./apps/backend/.env
    ports:
      - "8080:8080"
  
  frontend:
    container_name: rbo-frontend-prod
    command: npm run start
    build: 
      context: ./apps/frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3000:3000"
