name: Update package.json

on:
  create:
    branches:
      - "hotfix/*"
      - "release/*"

jobs:
  update-package-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: branch
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          VERSION=$(echo $branch_name | sed -E 's/(hotfix|release)\///')
          jq ".version = \"${VERSION}\"" package.json > temp.json && mv temp.json package.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "Update version to $VERSION in package.json"
          git push
